### ISSUE TITLE
firmware: sign_message fails

### ISSUE THREAD

**Issue by mcudev** [trezor/trezor-core#111]
```
> python2 trezorctl -v sign_message 'abc' -n "Bitcoin/0'/0/0"
...
SENDING <SignMessage> (38 bytes):
<SignMessage: {'message': 'abc', 'address_n': [2147483692, 2147483648, 2147483648, 0, 0], 'coin_name': u'Bitcoin', 'script_type': 0}>
RECEIVED <Failure> (18 bytes):
<Failure: {'message': u'Firmware error', 'code': 99}>
```
tried the same command against the emulator and got this:
```
$ make emu
./emu.sh
Traceback (most recent call last):
  File "/trezor-core/src/trezor/wire/__init__.py", line 128, in session_handler
  File "/trezor-core/src/trezor/wire/__init__.py", line 126, in session_handler
  File "/trezor-core/src/trezor/wire/__init__.py", line 162, in protobuf_workflow
  File "/trezor-core/src/trezor/wire/__init__.py", line 162, in protobuf_workflow
  File "/trezor-core/src/trezor/wire/__init__.py", line 151, in protobuf_workflow
  File "/trezor-core/src/trezor/utils.py", line 16, in inner
  File "/trezor-core/src/trezor/utils.py", line 11, in inner
  File "/trezor-core/src/apps/wallet/__init__.py", line 38, in dispatch_SignMessage
  File "/trezor-core/src/apps/wallet/sign_message.py", line 7, in <module>
  File "/trezor-core/src/apps/common/signverify.py", line 5, in <module>
  File "/trezor-core/src/apps/wallet/sign_tx/signing.py", line 14, in <module>
MemoryError: memory allocation failed, allocating 1280 bytes
```

**Comment by mcudev** [comment]
works now
