### ISSUE TITLE
firmware: recovery_device failure

### ISSUE THREAD

**Issue by mcudev** [trezor/trezor-core#112]
missing the second param, `needs_backup`.

```
> python2 trezorctl -v recovery_device

$ make emu
./emu.sh
Traceback (most recent call last):
  File "/trezor-core/src/trezor/wire/__init__.py", line 128, in session_handler
  File "/trezor-core/src/trezor/wire/__init__.py", line 126, in session_handler
  File "/trezor-core/src/trezor/wire/__init__.py", line 162, in protobuf_workflow
  File "/trezor-core/src/trezor/wire/__init__.py", line 162, in protobuf_workflow
  File "/trezor-core/src/trezor/wire/__init__.py", line 151, in protobuf_workflow
  File "/trezor-core/src/trezor/utils.py", line 16, in inner
  File "/trezor-core/src/trezor/utils.py", line 11, in inner
  File "/trezor-core/src/apps/management/recovery_device.py", line 41, in recovery_device
TypeError: load_mnemonic() takes 2 positional arguments but 1 were given
```

**Comment by mcudev** [comment]
@prusnak I meant to ask, do you guys have a GUI being tested for transaction signing? I'd like to test transaction signing with testnet (or small value altcoins -- understandably at my own risk) to see if any sighash bugs etc... fall out. Just looking to see if you have an easy way already setup?

**Comment by prusnak** [comment]
Most of the workflows are in flux now. Functionally they should be complete (unit tests pass), but GUI is yet to be finished.

**Comment by jpochyla** [comment]
Fixed in https://github.com/trezor/trezor-core/commit/fcd712a0b058b5a67718ed1f0de99d8bcdd6f8b1

**Comment by mcudev** [comment]
tested, good, thanks!
