### ISSUE TITLE
Fix getpublicnode for ed25519 curve

### ISSUE THREAD

**Issue by slush0** [trezor/trezor-core#141]
Currently, Trezor return malformed public node, which gets rejecting by trezor-agent (ssh).

```
Traceback (most recent call last):
  File "/usr/local/bin/trezor-agent", line 11, in <module>
    load_entry_point('trezor-agent', 'console_scripts', 'trezor-agent')()
  File "/home/user/projekty/trezor/trezor-agent/agents/trezor/trezor_agent.py", line 5, in <lambda>
    ssh_agent = lambda: libagent.ssh.main(DeviceType)
  File "/home/user/projekty/trezor/trezor-agent/libagent/ssh/__init__.py", line 159, in wrapper
    return func(*args, **kwargs)
  File "/home/user/projekty/trezor/trezor-agent/libagent/ssh/__init__.py", line 279, in main
    for pk in conn.public_keys():
  File "/home/user/projekty/trezor/trezor-agent/libagent/ssh/__init__.py", line 194, in public_keys
    self.public_keys_cache = conn.export_public_keys(self.identities)
  File "/home/user/projekty/trezor/trezor-agent/libagent/ssh/client.py", line 28, in export_public_keys
    curve_name=i.curve_name)
  File "/home/user/projekty/trezor/trezor-agent/libagent/formats.py", line 152, in decompress_pubkey
    raise ValueError(msg)
ValueError: invalid ed25519 public key: b'\x02{l\x01&\n.....<censored>'
```

...and add unit tests to python-trezor

**Comment by prusnak** [comment]
Fixed in 3971f4bf13725a2a35f09c607a65ad56832f3c9b and 1b8217ca669338cec9c1c8149a206d2d4d0c37d0
