### ISSUE TITLE
load_device not working

### ISSUE THREAD

**Issue by michal-novacek** [trezor/trezor-core#146]
Getting "Unexpected message" error in both trezorctl / web wallet

Bootloader 2.0.1 / Firmware 2.0.5 / trezorctl 0.9.1

> trezorctl load_device -m "all all all all all all all all all all all all"

```bash
Traceback (most recent call last):
  File "/usr/local/bin/trezorctl", line 851, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/bin/trezorctl", line 283, in load_device
    'SLIP-0014'
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 162, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 176, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 1120, in load_device_by_mnemonic
    skip_checksum=skip_checksum))
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 190, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 235, in call
    msg = handler(resp)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 247, in callback_Failure
    raise CallException(msg.code, msg.message)
trezorlib.client.CallException: (1, 'Unexpected message')```

**Comment by prusnak** [comment]
That is expected. Load Device call is disabled in production builds of the firmware.
