### ISSUE TITLE
Issue when entering passphrase

### ISSUE THREAD

**Issue by karel-3d** [trezor/trezor-core#212]
This issue appears when entering passphrase on current master. 

```
Traceback (most recent call last):                  
  File "/home/g/dev/trezor-core/src/trezor/wire/__init__.py", line 120, in session_handler               
  File "/home/g/dev/trezor-core/src/trezor/wire/__init__.py", line 117, in session_handler               
  File "/home/g/dev/trezor-core/src/trezor/wire/__init__.py", line 153, in protobuf_workflow             
  File "/home/g/dev/trezor-core/src/trezor/wire/__init__.py", line 153, in protobuf_workflow             
  File "/home/g/dev/trezor-core/src/trezor/wire/__init__.py", line 142, in protobuf_workflow             
  File "/home/g/dev/trezor-core/src/apps/wallet/get_public_key.py", line 17, in get_public_key           
  File "/home/g/dev/trezor-core/src/apps/common/seed.py", line 10, in derive_node                        
  File "/home/g/dev/trezor-core/src/apps/common/seed.py", line 21, in _get_cached_seed                   
  File "/home/g/dev/trezor-core/src/apps/common/seed.py", line 29, in _get_cached_passphrase             
  File "/home/g/dev/trezor-core/src/apps/common/request_passphrase.py", line 74, in protect_by_passphrase
  File "/home/g/dev/trezor-core/src/apps/common/request_passphrase.py", line 68, in request_passphrase   
  File "/home/g/dev/trezor-core/src/trezor/ui/__init__.py", line 120, in inner                           
  File "/home/g/dev/trezor-core/src/trezor/ui/__init__.py", line 117, in inner                           
  File "/home/g/dev/trezor-core/src/apps/common/request_passphrase.py", line 57, in request_passphrase_ack                                                                                                         
TypeError: unexpected keyword argument 'state'
```

This does not happen with latest stable, v2.0.6

**Comment by prusnak** [comment]
Fixed in f6be3899eb4ebbdb659799d587ed490072ddecc3
