### ISSUE TITLE
Inconsistent behavior when requesting Ethereum address

### ISSUE THREAD

**Issue by mlejva** [trezor/trezor-core#269]
When [`ethereum_get_address`](https://github.com/trezor/trezor-core/blob/master/src/apps/ethereum/get_address.py#L5) is called with the path format `m/number` (for example `m/44'`) Trezor might return following `Failure_Firmware` error. 
```
Traceback (most recent call last):
  File "/Users/vasekmlejnsky/Developer-Work/trezor-core/src/trezor/wire/__init__.py", line 120, in session_handler
  File "/Users/vasekmlejnsky/Developer-Work/trezor-core/src/trezor/wire/__init__.py", line 117, in session_handler
  File "/Users/vasekmlejnsky/Developer-Work/trezor-core/src/trezor/wire/__init__.py", line 153, in protobuf_workflow
  File "/Users/vasekmlejnsky/Developer-Work/trezor-core/src/trezor/wire/__init__.py", line 153, in protobuf_workflow
  File "/Users/vasekmlejnsky/Developer-Work/trezor-core/src/trezor/wire/__init__.py", line 142, in protobuf_workflow
  File "/Users/vasekmlejnsky/Developer-Work/trezor-core/src/apps/ethereum/get_address.py", line 20, in ethereum_get_address
IndexError: list index out of range
```
The error is throw only when address should be displayed on a device -  [line 19](https://github.com/trezor/trezor-core/blob/master/src/apps/ethereum/get_address.py#L19). And caused by [line 20](https://github.com/trezor/trezor-core/blob/master/src/apps/ethereum/get_address.py#L20)

I'm not sure whether this is a real issue since the path format is not itself valid - the process should fail. Problem is that an address might or might not be returned - depending on whether the address should be displayed or not.

**Comment by jpochyla** [comment]
Fixed in 2f6386e, thank you!
